[package]
name = "scanner"
version = "0.1.0"
edition = "2024"

license = "MIT"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
soapysdr = "0.4.2"
thiserror = "1.0"
cpal = "0.15"

rustfft = "6.4.0"

